<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AIMonitor.Core\AIMonitor.Core.csproj" />
    <ProjectReference Include="..\AIMonitor.Workflow\AIMonitor.Workflow.csproj" />
    <ProjectReference Include="..\AIMonitor.Runtime\AIMonitor.Runtime.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>